### ISSUE TITLE
OrderedDict for SemanticsDict and FeatureDict

### ISSUE THREAD

**Issue by murawaki** [ku-nlp/rhoknp#103]
We sometimes want to preserve the original order of 意味情報 and 素性, especially when we modify KNP files using rhoknp. How about switching from Dict to OrderedDict?

**Comment by hkiyomaru** [comment]
In Python 3.6 and later, the built-in `dict` type preserves the order of insertion, so rhoknp should already have support for this. I've confirmed that the following unit test has been passed.

```python
def test_modification():
    features = FeatureDict.from_fstring("""<用言:動><主節>""")
    assert features.to_fstring() == """<用言:動><主節>"""
    # Update
    features["用言"] = "判"
    assert features.to_fstring() == """<用言:判><主節>"""
    # Insert
    features["文末"] = True
    assert features.to_fstring() == """<用言:判><主節><文末>"""
```

If you encountered a problem, could you provide the minimal code to reproduce it?

**Comment by murawaki** [comment]
Thanks. Actually I later found that the distortion of ordering is caused by the mixture of FeatureDict and MemoTag, not by FeatureDict itself.
