### ISSUE TITLE
fail to parse KNBC's ./corpus1/KN041_Kyoto_1/KN041_Kyoto_1-1-1-01

### ISSUE THREAD

**Issue by murawaki** [ku-nlp/rhoknp#68]
`ValueError: malformed line: ［ ［ ［ 特殊 1 括弧始 3 * 0 * 0 NIL <文頭><記英数カ><英記号><記号><括弧始><括弧><接頭><非独立接頭辞><タグ単位始><文節始>`

**Comment by hkiyomaru** [comment]
I found that the file format is broken (a line to represent a basic-phrase delimiter is missing). This doesn't seem to be a rhoknp's problem.
