### ISSUE TITLE
Is it possible to support Python3.7?

### ISSUE THREAD

**Issue by conan1024hao** [ku-nlp/rhoknp#93]
Hi, I want to update pyknp in [BertJapaneseTokenizer](https://github.com/huggingface/transformers/blob/v4.25.1/src/transformers/models/bert_japanese/tokenization_bert_japanese.py#L107) to rhoknp. But since transformers is still based on Python3.7, there will be a version conflict.
Is it possible to support Python3.7?

**Comment by hkiyomaru** [comment]
Thank you for your feature request! We will address this in the next few days.

**Comment by nobu-g** [comment]
We have released `rhoknp` v1.1.0, which supports Python 3.7.

**Comment by conan1024hao** [comment]
@nobu-g Thanks for updating! Now `transformers` supports `rhoknp`! https://github.com/huggingface/transformers/pull/20890
